version: '3'
services:
  postgres:
    image: postgres:14.0
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: elice
    volumes:
      - /opt/homebrew/var/postgresql@14/data:/var/lib/postgresql/data
    container_name: postgres_docker
    networks:
      - default

  redis:
    image: redis:6.2.5
    restart: always
    ports:
      - "6379:6379"
    networks:
      - default
    extra_hosts:
        - "host.docker.internal:host-gateway"

  web:
    image: elice_interview:0.1
    restart:
        always
    ports:
      - "8000"
    environment:
      DB_HOST: postgres_docker
      RDB: postgresql+asyncpg
      DB_PORT: 5432
      DB_NAME: elice
      DB_USER: postgres
      DB_PASSWORD: 1234
      REDIS_HOST: host.docker.internal
    depends_on:
        - postgres
    networks:
      - default
    external_links:
      - redis

volumes:
  postgres_data:
    driver: local

networks:
  default: